# FT-Transformer default architecture parameters -------------------------------------------------------------------------#
out_features   : 1
d_token        : 72
n_layers       : 3
n_heads        : 8
d_ffn_factor   : 1.33
dropout        : 0.35
activation     : reglu
norm_first     : true
token_bias     : true
layer_norm_eps : 1.0e-5
bias           : true
#--------------------------------------------------------------------------------------------------------------------------#
