# Default hyperparameters for XGBoost model using booster=dart
booster: dart
n_estimators: 100
learning_rate: 0.1
max_depth: 6
random_state: 42
verbosity: 0

# DART-specific parameters
sample_type: uniform       
normalize_type: tree       
rate_drop: 0.1             
skip_drop: 0.0             
