# Default hyperparameters for LightGBM model
boosting_type: "gbdt"
n_estimators: 100
learning_rate: 0.1
max_depth: 6
num_leaves: 31
subsample: 0.8
colsample_bytree: 0.8
reg_alpha: 0.0
reg_lambda: 0.0
random_state: 42
verbosity: -1
force_col_wise: true 